import org.jetbrains.kotlin.gradle.dsl.JvmTarget

// Generated by scripts/generate.sh (buf) and committed; never edit src/generated by hand.
plugins {
    `java-library`
    alias(libs.plugins.kotlin.jvm)
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
}

sourceSets {
    main {
        java.srcDir("src/generated/java")
        kotlin.srcDir("src/generated/kotlin")
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.release.set(17)
    // Generated code: don't fail on its warnings.
    options.compilerArgs.add("-Xlint:none")
}

dependencies {
    api(libs.protobuf.javalite)
    api(libs.connect.okhttp)
    api(libs.connect.javalite)

    testImplementation(libs.junit)
}
