// swift-tools-version: 6.0
// LoamsProto: SwiftProtobuf messages and connect-swift clients generated by buf from proto/
// (scripts/generate.sh). The generated files are committed; never edit them by hand.
import PackageDescription

let package = Package(
    name: "LoamsProto",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [.library(name: "LoamsProto", targets: ["LoamsProto"])],
    dependencies: [
        .package(url: "https://github.com/connectrpc/connect-swift.git", exact: "1.2.3"),
        .package(url: "https://github.com/apple/swift-protobuf.git", from: "1.38.1"),
    ],
    targets: [
        .target(
            name: "LoamsProto",
            dependencies: [
                .product(name: "Connect", package: "connect-swift"),
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
            ],
            // Generated code: Swift 5 mode keeps generator-owned files out of strict concurrency.
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ]
)
